# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#
#
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
  
variables:
- group: docker
- name: imageName
  value: thought-api
steps:
- script: |
    docker build -t $(acrRepo).azurecr.io/$(imageName):$(Build.BuildNumber) .
    docker login -u $(acrUser) -p $(dockerPassword) $(acrRepo).azurecr.io
    docker push $(acrRepo).azurecr.io/$(imageName):$(Build.BuildNumber)
