# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: docker
steps:
- script: |
    docker build -t $(dockerRepo)/$(Build.Repository.Name):$(Build.BuildNumber) .
    docker build -t $(dockerRepo)/$(Build.Repository.Name):latest .
    docker login -u $(dockerUser) -p $(dockerPassword) $(dockerRepo).azurecs.io
    docker push $(dockerRepo)/$(Build.Repository.Name):$(Build.BuildNumber)
    docker push $(dockerRepo)/$(Build.Repository.Name):latest
  displayName: 'Build and push to docker repo'
