pipeline {
    agent none
    environment {
        ENV = "dev"
    }
    parameters {
         string(defaultValue: "DEV", description: 'Environment to deploy to?', name: 'ENV')
    }
    stages {
        stage('Build') {
            steps {
                    echo "Building....."
            }
        }
        stage('Deploy BETA') {
            steps {
                    echo "Deploying BETA....."
            }
        }
        stage('Test Beta Services ') {
            steps {
                    echo "Testing Beta....."
            }
        }
        stage('Deploy LIVE') {
            steps {
                    echo "Deploying LIVE....."
            }
        }
        stage('Test LIVE') {
            steps {
                    echo "Testing Live....."
            }
        }
    }
}
