pipeline {
    agent any
    environment {
        ENV = "dev"
    }
    parameters {
         string(defaultValue: "DEV", description: 'Environment to deploy to?', name: 'ENV')
    }
    stages {
        stage('Build') {
            steps {
                    echo "Building....."
                    sh "docker build -t azureHackathon.azurecr.io/thoughtapi:${BUILD_NUMBER} ."
                    sh "docker push -t azureHackathon.azurecr.io/thoughtapi:${BUILD_NUMBER}"
            }
        }
        stage('Deploy BETA') {
            steps{
                git branch: 'master',
                    url: 'https://github.com/azurehackathon/cdorchestrator.git'
                echo "Success"
            }
        }
        stage('Test Beta Services ') {
            steps {
                    echo "Testing Beta....."
            }
        }
        stage('Deploy LIVE') {
            steps {
                    echo "Deploying LIVE....."
            }
        }
        stage('Test LIVE') {
            steps {
                    echo "Testing Live....."
            }
        }
    }
}
